name: Deploy to Droplet

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Copy the repo to the droplet
      - name: Copy files to Droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLETIP }}
          username: ${{ secrets.DROPLET_SSH_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "."
          target: "/opt/slumhouse-bot"

      # Configure & restart service on the droplet
      - name: Configure and start service on Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLETIP }}
          username: ${{ secrets.DROPLET_SSH_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            set -euo pipefail

            APP_DIR=/opt/slumhouse-bot
            cd "$APP_DIR"

            # Ensure Python & venv
            sudo apt-get update -y
            sudo apt-get install -y python3 python3-venv python3-pip

            # Create .env on the droplet from your GitHub Secrets
            cat > .env <<'EOF'
            ADMIN_USER_ID=${{ secrets.ADMIN_USER_ID }}
            ALPACA_API_BASE_URL=${{ secrets.ALPACA_API_BASE_URL }}
            ALPACA_API_KEY_ID=${{ secrets.ALPACA_API_KEY_ID }}
            # optional: add this secret in GitHub later if you need it
            ALPACA_API_SECRET_KEY=${{ secrets.ALPACA_API_SECRET_KEY }}

            DIGITALOCEAN_API_TOKEN=${{ secrets.DIGITALOCEAN_API_TOKEN }}

            DISCORD_ALERT_CHANNEL_ID=${{ secrets.DISCORD_ALERT_CHANNEL_ID }}
            DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
            DISCORD_CLIENT_ID=${{ secrets.DISCORD_CLIENT_ID }}
            DISCORD_GUILD_ID=${{ secrets.DISCORD_GUILD_ID }}

            FINNHUB_API_KEY=${{ secrets.FINNHUB_API_KEY }}

            GHUB_TOKEN=${{ secrets.GHUB_TOKEN }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

            STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}
            STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
            STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}
            EOF

            # Virtualenv & deps
            python3 -m venv .venv
            . .venv/bin/activate
            pip install --upgrade pip
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt
            fi

            # Systemd unit for always-on bot
            sudo bash -c 'cat > /etc/systemd/system/slumhouse-bot.service <<UNIT
            [Unit]
            Description=Slum House Discord Bot
            After=network.target

            [Service]
            WorkingDirectory=/opt/slumhouse-bot
            EnvironmentFile=/opt/slumhouse-bot/.env
            ExecStart=/opt/slumhouse-bot/.venv/bin/python3 /opt/slumhouse-bot/bot.py
            Restart=always
            RestartSec=5
            User=root

            [Install]
            WantedBy=multi-user.target
            UNIT'

            sudo systemctl daemon-reload
            sudo systemctl enable slumhouse-bot.service
            sudo systemctl restart slumhouse-bot.service

            # Quick status to logs
            sudo systemctl --no-pager -l status slumhouse-bot.service || true
