- name: Install deps & restart service
  env:
    USER: ${{ secrets.DROPLET_SSH_USER }}
    HOST: ${{ secrets.DROPLET_IP }}
  run: |
    ssh -i ~/.ssh/id_ci "${USER}@${HOST}" 'bash -s' <<'REMOTE'
    set -euo pipefail
    cd /root/Bot-deploy

    # venv + deps
    python3 -m venv .venv || true
    source .venv/bin/activate
    pip install --upgrade pip setuptools wheel
    if [ -f requirements.txt ]; then
      pip install -r requirements.txt
    else
      pip install -U py-cord requests yfinance PyPDF2 nltk python-dotenv
    fi

    # download NLTK data (non-fatal if it flakes)
    python - <<'PY'
import nltk, sys
for p in ["punkt", "stopwords"]:
    try:
        nltk.download(p, quiet=True)
    except Exception as e:
        print("NLTK warn:", e, file=sys.stderr)
PY

    # restart the service and show tail
    systemctl daemon-reload
    systemctl restart slumhousebot || true
    systemctl enable  slumhousebot || true
    systemctl status  slumhousebot --no-pager || true
    journalctl -u slumhousebot -n 50 --no-pager || true
REMOTE
